const { INFAMY_REWARD } = require("./market/constants");
const {
    addCoins,
    findCharacterByName,
    getCharacterById,
    getCoins,
    getCurrentInfamyBoard,
    getMarketState,
    getRankAdjustmentHistory,
    getRankedCharacters,
    incrementWeeklyDivorces,
    processInfamyReset,
    registerCharacterFromDrop,
    saveMarketState,
    setCharacterManualRankAdjustment,
    setCoins,
    updateCharacterMarketEntry,
} = require("./market/repository");
const {
    createAdminCoinsEmbed,
    createAdminInfamyResetEmbed,
    createAdminRankEmbed,
    createAdminRankHistoryEmbed,
    createCharacterProfileEmbed,
    createCoinsEmbed,
    createInfamyEmbed,
    createMetaEmbed,
    createTopCharactersEmbed,
} = require("./market/embeds");
const { sortCharactersByRank } = require("./market/service");

module.exports = {
    INFAMY_REWARD,
    addCoins,
    createAdminCoinsEmbed,
    createAdminInfamyResetEmbed,
    createAdminRankEmbed,
    createAdminRankHistoryEmbed,
    createCharacterProfileEmbed,
    createCoinsEmbed,
    createInfamyEmbed,
    createMetaEmbed,
    createTopCharactersEmbed,
    findCharacterByName,
    getCharacterById,
    getCoins,
    getCurrentInfamyBoard,
    getMarketState,
    getRankAdjustmentHistory,
    getRankedCharacters,
    incrementWeeklyDivorces,
    processInfamyReset,
    registerCharacterFromDrop,
    saveMarketState,
    setCharacterManualRankAdjustment,
    setCoins,
    sortCharactersByRank,
    updateCharacterMarketEntry,
};
