const CHARACTER_REGISTRY_KEY = "market:characters";
const MARKET_RANK_HISTORY_KEY = "market:rank-history";
const MARKET_STATE_KEY = "market:state";
const USER_COINS_PREFIX = "coins:";
const INFAMY_REWARD = 100;
const INFAMY_RESET_MS = 7 * 24 * 60 * 60 * 1000;
const RARITY_MIN = 1.0;
const RARITY_MAX = 1.5;
const BASE_SCORE_WEIGHT = 0.5;
const DIVORCE_PENALTY_POINTS = 2.5;
const INFAMY_CLAIM_VALUE_MULTIPLIER = 0.92;
const INFAMY_RANK_PENALTY = 3;
const MARKET_ICON = "https://nhentai.net/static/favicon-32x32.png";
const MANUAL_RANK_ADJUSTMENT_CAP = 100;
const PRESTIGE_FAVORITE_POINTS = 7;
const PRESTIGE_OWNER_POINTS = 4;
const PRESTIGE_TENURE_CAP = 16;
const PRESTIGE_TENURE_PER_WEEK = 2;
const RARITY_SCORE_MULTIPLIER = 14;

module.exports = {
    BASE_SCORE_WEIGHT,
    CHARACTER_REGISTRY_KEY,
    MARKET_RANK_HISTORY_KEY,
    DIVORCE_PENALTY_POINTS,
    INFAMY_CLAIM_VALUE_MULTIPLIER,
    INFAMY_RANK_PENALTY,
    INFAMY_REWARD,
    INFAMY_RESET_MS,
    MANUAL_RANK_ADJUSTMENT_CAP,
    MARKET_ICON,
    MARKET_STATE_KEY,
    PRESTIGE_FAVORITE_POINTS,
    PRESTIGE_OWNER_POINTS,
    PRESTIGE_TENURE_CAP,
    PRESTIGE_TENURE_PER_WEEK,
    RARITY_MAX,
    RARITY_MIN,
    RARITY_SCORE_MULTIPLIER,
    USER_COINS_PREFIX,
};
