const HELPER_STATS_PREFIX = "helper_stats:";
const HELPER_REACTION_EMOJI = "💎";
const HELPER_DROP_DURATION_SECONDS = 12;
const HELPER_DROP_CHANCE = 0.35;
const HELPER_MIN_REWARD = 15;
const HELPER_MAX_REWARD = 90;

module.exports = {
    HELPER_DROP_CHANCE,
    HELPER_DROP_DURATION_SECONDS,
    HELPER_MAX_REWARD,
    HELPER_MIN_REWARD,
    HELPER_REACTION_EMOJI,
    HELPER_STATS_PREFIX,
};
